apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-api
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-api
  template:
    metadata:
      labels:
        app: fastapi-api
    spec:
      containers:
      - name: fastapi-api
        image: fastapi:latest 
        imagePullPolicy: IfNotPresent 
        command: ["opentelemetry-instrument"]
        args: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://alloy.monitoring.svc:4317" # Point to Alloy
        - name: DATABASE_URL
          value: "postgresql://user:password@postgres:5432/postgres"
        - name: OTEL_SERVICE_NAME
          value: "fastapi-server"
        - name: OTEL_LOGS_EXPORTER
          value: "otlp" # Ensure logs are also sent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-api
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-api
  template:
    metadata:
      labels:
        app: proxy-api
    spec:
      containers:
      - name: proxy-api
        image: proxy-app:latest
        imagePullPolicy: IfNotPresent 
        command: ["opentelemetry-instrument"]
        args: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
        ports:
        - containerPort: 8001
        env:
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://alloy.monitoring.svc:4317" # Point to Alloy
        - name: OTEL_SERVICE_NAME
          value: "proxy-api"
        - name: FASTAPI_URL
          value: "http://fastapi-api:8000/rolldice"