services:
  # The LGTM all-in-one backend
  lgtm:
    image: grafana/otel-lgtm:latest
    volumes:
      - ./loki.yaml:/etc/grafana/provisioning/datasources/loki.yaml:ro
    ports:
      - "3000:3000"      
      - "4317:4317"     
      - "4318:4318"
    networks:
      - lgtm-demo

  # The Telemetry Pipeline
  alloy:
    image: grafana/alloy:latest
    volumes:
      - ./config.river:/etc/alloy/config.river
    command: run --server.http.listen-addr=0.0.0.0:12345 --stability.level=experimental /etc/alloy/config.river
    ports:
      - "12345:12345"
      - "12346:4317"
    networks:
      - lgtm-demo

  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - lgtm-demo

  # FastAPI Application
  app:
    build: ./fastapi
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_SERVICE_NAME=fastapi-app
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=postgres
      - OTEL_PYTHON_LOG_CORRELATION=true
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_LOG_LEVEL=debug
      - OTEL_PYTHON_LOG_LEVEL=debug
      
    command: opentelemetry-instrument uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
    - "8000:8000"
    depends_on:
      - alloy
      - db
    networks:
      - lgtm-demo
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://user:password@db:5432/postgres?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - db
    networks:
      - lgtm-demo
    
  proxy-app:
    build: ./fastapi_proxy
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4317
      - OTEL_SERVICE_NAME=proxy-app
      - UPSTREAM_URL=http://app:8000/rolldice
      - OTEL_LOGS_EXPORTER=otlp            
      - OTEL_PYTHON_LOG_CORRELATION=true   
      - OTEL_TRACES_EXPORTER=otlp     
      - OTEL_METRICS_EXPORTER=otlp
    ports:
      - "8001:8000"
    networks:
      - lgtm-demo
    depends_on:
      - alloy
      - app
    command: >
      opentelemetry-instrument 
      python main.py
    

      
    
networks:
  lgtm-demo: