apiVersion: v1
kind: Service
metadata:
  name: alloy
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: alloy
  ports:
    - name: http-metrics
      port: 12345
      targetPort: 12345
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318