{{- range $name, $config := .Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
spec:
  replicas: {{ $config.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: {{ $config.image }}
          imagePullPolicy: {{ $config.imagePullPolicy | default "IfNotPresent" }}
          command:
            {{- range $config.command }}
            - {{ . | quote }}
            {{- end }}
          args:
            {{- range $config.args }}
            - {{ . | quote }}
            {{- end }}
          ports:
            - containerPort: {{ $config.port }}
          env:
            - name: OTEL_SERVICE_NAME
              value: {{ $name | quote }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://docker-otel-lgtm-alloy:4317"
            - name: OTEL_PYTHON_LOG_CORRELATION
              value: "true"
            - name: UPSTREAM_URL
              value: {{ $config.upstreamUrl | default "" | quote }}
            - name: DATABASE_URL
              value: {{ $config.databaseUrl | default "" | quote }}
            {{- if $config.env }}
            {{- range $key, $val := $config.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- end }}
            {{- if eq $name "postgres-db" }}
          volumeMounts:
              - name: init-sql-volume
                mountPath: /docker-entrypoint-initdb.d
            {{- end }}
        {{- if eq $name "postgres-db" }}
      volumes:
        - name: init-sql-volume
          configMap:
            name: postgres-init-sql
      {{- end }}

     
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  type: {{ $config.serviceType | default "ClusterIP" }}
  selector:
    app: {{ $name }}
  ports:
    - protocol: TCP
      port: {{ $config.port }}
      targetPort: {{ $config.port }}
      {{- if eq $config.serviceType "LoadBalancer" }}
      nodePort: {{ $config.nodePort | default "" }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432