apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres-db.fullname" . }}
  labels:
    {{- include "postgres-db.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "postgres-db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "postgres-db.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "postgres-db.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresVars.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresVars.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresVars.database | quote }}
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: init-db
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
              {{- with .Values.volumeMounts }}
              {{- toYaml . | nindent 12 }}
              {{- end }}
        
      # volumes must be outside the containers array, but inside the spec
      volumes:
        - name: init-db
          configMap:
            name: {{ include "postgres-db.fullname" . }}-init
          {{- with .Values.volumes }}
          {{- toYaml . | nindent 8 }}
          {{- end }}
        
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}